org.gradle.jvmargs=-Xmx8G -Dorg.gradle.logging.level=warn -Djava.util.concurrent.ForkJoinPool.common.parallelism=1
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_id=immersivegeology
mod_name=Immersive Geology
mod_authors=Muddykat-Tech and UnSchtalch
mod_license=LGPL-3.0
mod_description=Immersive Geology for Minecraft 1.21.1 on NeoForge.
